Feat: Add Iris Server Support
deepmap/oapi-codegen pull request #1088
Opened 2023-06-06 14:26 UTC by Ns2Kracy

Not finished yet

2023-06-07 09:32 UTC, Ns2Kracy commented
@deepmap-marcinr  if there is anyone available on the team who can review it?

2023-06-08 08:46 UTC, jamietanna commented
Thanks for your first contribution and it's a big one 🙌  We'll try and review soon - there's a few things we'll want to get in following the v1.13.0 release for a patch bump, then can look at this one

2023-06-09 03:58 UTC, Ns2Kracy commented
> 

Looking forward for it!

2023-06-09 08:12 UTC, alexandear requested changes

2023-06-09 08:12 UTC, alexandear commented on pkg/iris-middleware/oapi_validate.go
> +		return nil, fmt.Errorf("error reading %s: %s", path, err)
Could we use native error wrapping?

```suggestion
		return nil, fmt.Errorf("error reading %s: %w", path, err)
```

2023-06-09 08:12 UTC, alexandear commented on pkg/iris-middleware/oapi_validate.go
> +		return nil, fmt.Errorf("error parsing %s as Swagger YAML: %s",
```suggestion
		return nil, fmt.Errorf("error parsing %s as Swagger YAML: %w",
```

2023-06-09 08:12 UTC, alexandear commented on pkg/iris-middleware/oapi_validate.go
> +			return fmt.Errorf("error validating route: %s", err.Error())
```suggestion
			return fmt.Errorf("error validating route: %w", err)
```

2023-06-09 08:12 UTC, alexandear commented on pkg/iris-middleware/oapi_validate.go
> +			return fmt.Errorf("error validating request: %s", err)
```suggestion
			return fmt.Errorf("error validating request: %w", err)
```

2023-06-09 08:12 UTC, alexandear requested changes
Cool.

I left some comments.

2023-06-10 02:08 UTC, Ns2Kracy commented
> Cool.
> 
> I left some comments.

I'll finish it

2023-06-10 02:22 UTC, Ns2Kracy commented on pkg/codegen/operations.go
> +// GenerateIrisServer This function generates all the go code for the ServerInterface as well as
This is modified from echo, maybe no modification is needed?

2023-06-11 16:09 UTC, alexandear approved these changes

2023-06-12 05:07 UTC, Ns2Kracy commented
I think all the work is basically done! Great!

2023-07-28 22:57 UTC, deepmap-marcinr commented
Thank you for doing this.

I need to find a way of abstracting away all these different routers behind a stable interface for template code. It'd be nice if oapi-codegen could simply import someone else's code generator as a module.

2023-08-28 19:18 UTC, jamietanna requested changes
Will require a couple of tweaks - looks like we may be missing the changes added for #1168 (as they were completed after this PR was first raised) - happy to add them for you!

2023-08-28 19:26 UTC, jamietanna approved these changes

2023-08-28 19:44 UTC, merged

2023-08-29 00:18 UTC, Ns2Kracy commented
> Will require a couple of tweaks - looks like we may be missing the changes added for #1168 (as they were completed after this PR was first raised) - happy to add them for you!

Thanks!

2023-10-17 08:47 UTC, lzap commented
Just to give you little feedback, this feature pulled a ton of dependencies which are no longer 1.19 compatible. The only solution for now is to freeze oapi-codegen until our Go runtime provider will upgrade the stack. Would be awesome to separate generators from the runtime at some point.

Anyways, thanks for the project it works really well. We use just the plain good old Go standard library :-D

2023-10-17 08:53 UTC, jamietanna commented
Thanks @lzap! Yes we're aware, we made some work towards this recently based on https://github.com/deepmap/oapi-codegen/issues/1142.

By November there's [a v2 planned (which is very minor breaking changes, should be zero work for almost all consumers)](https://github.com/deepmap/oapi-codegen/discussions/1309) which removes the transitive dependencies that you'll be seeing due to the current package structure, which will reduce the number + size of the dependency tree considerably.

If you check out [this comment](https://github.com/deepmap/oapi-codegen/discussions/1309#discussioncomment-7238363) you should be able to pin to [the proposed changes](https://github.com/deepmap/oapi-codegen/pull/1310) to see that you may be OK. Additionally, by moving to [v1.15.0: Remove issues with Go 1.21](https://github.com/deepmap/oapi-codegen/releases/tag/v1.15.0) you won't be required to use Go 1.21. The minimum required Go version is 1.20 as [Go 1.19 is no longer supported](https://endoflife.date/go).

2023-10-17 09:01 UTC, jamietanna commented
> We use just the plain good old Go standard library :-D

You may also be interested in https://github.com/deepmap/oapi-codegen/issues/1068 which looks likely to land in Go 1.22

2023-10-17 12:09 UTC, lzap commented
Thanks for the extra work, that had to be ton of code to do that. Awesome.