Feature: Expose constants for the context keys that pass expected security scopes
deepmap/oapi-codegen pull request #258
Opened 2020-11-30 12:16 UTC by maclav3

## What changed

The context keys used when adding scopes of a security scheme are exported as constants, one per each security scheme.
This should enable depedent code to read the scopes more reliably via:

```go
scopes := ctx.Value(types.BearerTokenScopes)
```

instead of the hardcoded:

```go
scopes := ctx.Value("bearerToken.Scopes")
```

## Rationale

An effective way to check permissions for API operations is to write a middleware that takes the expected security scopes for the operation, and confronts them with the scopes that are present for the request.

Exposing the context key as a `const` increases safety by enabling compile-time checking, prevents typos and unexpected errors.

## Notes

I made an attempt to expose more constants, like operation IDs (which could be passed as context values) and paths for each operation: https://github.com/deepmap/oapi-codegen/compare/v1.4.1...maclav3:expose-constants

However, I decided that it was too opinionated, and I don't really have good enough use cases for that.
This adds only the context key for security scopes, but I retained the constants templating mechanism, because it is extensible in case there's a need to expose more constants in the future.

I thought to make the context key a private type, like recommended in https://golang.org/pkg/context/#WithValue:
```go
type contextKey string
```
> The provided key must be comparable and should not be of type string or any other built-in type to avoid collisions between packages using context. Users of WithValue should define their own types for keys

but this doesn't work with `echo.Context.Set`, which expects a `string`.
Made no sense to generate different types for `server` and `chi-server`, so I retained the `string`.

2020-12-03 10:41 UTC, maclav3 commented on pkg/codegen/templates/constants.tmpl
> +    {{- $ProviderName | ucFirst}}Scopes = "{{$ProviderName}}.Scopes"
This is useful when generating a server, less so with a client
I didn't want to overcomplicate the PR by generating this only when `server|chi-server` is chosen, but maybe I should?

2021-01-05 16:41 UTC, deepmap-marcinr requested changes
Please run "make generate" since your change requires regenerating all generated code. This is why the precommit failed.

2021-01-05 16:41 UTC, deepmap-marcinr commented on pkg/codegen/codegen.go
> +// Generates operation ids, context keys, paths, etc. to be exported as constants
This comment is out of date with the code.

2021-01-05 16:41 UTC, deepmap-marcinr commented on pkg/codegen/codegen.go
> +	providerNames := map[string]struct{}{}
We've been using map[string]bool for a map of key presence. It allows for `if foo[x]`. It's nice to stick to one style.

2021-01-30 00:01 UTC, merged

2021-02-08 17:34 UTC, mitar commented
This broke our generated code. It ends up generating:

```
const (
Access-tokenScopes = "access-token.Scopes"

)
```

Relevant part of our spec (in YAML):

```
  securitySchemes:
    access-token:
      type: http
      scheme: bearer
      bearerFormat: |
        JWT-format access token.

security:
  - access-token: []
```

2021-02-08 17:37 UTC, mitar commented
It seems there is no way to disable generating those constants.

2021-02-08 17:40 UTC, deepmap-marcinr commented
Thanks for reporting this. I'll get it fixed asap. These things are so fragile!

2021-02-08 17:59 UTC, deepmap-marcinr commented
Try v1.5.1, it should fix your issue while preserving the enums.

I really need to refactor this code to sanitize names better...

On Mon, Feb 8, 2021 at 9:37 AM Mitar <notifications@github.com> wrote:

> It seems there is no way to disable generating those constants.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/deepmap/oapi-codegen/pull/258#issuecomment-775317850>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALKC5DDKOG7RNGJ2W5MX4EDS6AOPDANCNFSM4UHPS23A>
> .
>

2021-02-08 18:07 UTC, mitar commented
Thanks! It works (compiles). The output is pretty ugly though:

```
Access_tokenScopes = "access_token.Scopes"
```

2021-02-08 18:51 UTC, deepmap-marcinr commented
Yes, I agree, but at least it works now. Step 2 is to make it less ugly
later.

On Mon, Feb 8, 2021 at 10:08 AM Mitar <notifications@github.com> wrote:

> Thanks! It works (compiles). The output is pretty ugly though:
>
> Access_tokenScopes = "access_token.Scopes"
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/deepmap/oapi-codegen/pull/258#issuecomment-775337258>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALKC5DH4MXJF4ZYFJGPOCMTS6ASAXANCNFSM4UHPS23A>
> .
>