Embed spec v2
deepmap/oapi-codegen pull request #327
Opened 2021-03-26 19:51 UTC by dududko

This PR adds the same feature as #320 except for the part that the old PR was based on the new feature in go 1.16 - embed directives, whereas this PR is based on the old -fashion way of embedding content of the spec file in the golang variable as the base64 encoded zipped value.
Due to this change all builds and tests are passed. 
Feel free to review the code and request changes or additional explanation.

2021-04-02 21:11 UTC, deepmap-marcinr requested changes

2021-04-02 21:11 UTC, deepmap-marcinr commented on go.mod
> +	github.com/getkin/kin-openapi v0.49.0
Could you rebase and use v0.53.0? The version you're using still forces Go 1.16 because kin-openapi has //embed directives.

2021-04-03 12:01 UTC, dududko commented
@deepmap-marcinr done

2021-04-03 20:53 UTC, merged

2021-04-06 09:06 UTC, wangyoucao577 commented
It's really great! Thanks!