Chain Chi middlewares in reverse order so they execute first-to-last
deepmap/oapi-codegen pull request #787
Opened 2022-10-14 05:45 UTC by ericvolp12

Resolves reversed-ordering of Chi middleware chaining.

After this change, Chi middlewares will be applied in first-to-last ordering i.e. earlier wired/invoked middlewares will run before later wired middlewares.

This addresses https://github.com/deepmap/oapi-codegen/issues/687 and https://github.com/deepmap/oapi-codegen/issues/786

Not sure how I'd go about testing this since the existing unit tests don't seem to have complex middlewares, could use some advice if we want to include a unit test for this.

2022-10-14 05:47 UTC, ericvolp12 commented
Oh, I just realized these issues were already addressed in https://github.com/deepmap/oapi-codegen/pull/688 but it didn't end up being followed-up on.

2022-10-15 09:58 UTC, jamietanna requested changes
Hey, thanks for this - I think we'll need to make this an opt-in configurable change, rather than a breaking change.

The breaking change _I think_ you're referring to is when we changed the change to how to invoke the generator?

Although, yes, we could've rolled that out in a less breaking fashion, I think that's more noticeable as a breaking change to us subtly changing underlying behaviour, which may not be clear to consumers, and break a lot of applications.

2022-10-15 18:10 UTC, ericvolp12 commented
I was more referencing this rollback release after we broke the type signature of some of the generated code for Gin - https://github.com/deepmap/oapi-codegen/releases/tag/v1.8.1

I'll look into turning this into a configuration-driven change though it might be a few days before I can get around to it.

2022-10-15 19:25 UTC, ericvolp12 commented
Okay JK I got bored and decided to work on this.

The changes as shown now pass a new `TemplateParameters` object into the template engine which include an `Operations` property that is the old `ops` object that used to be the root of most templates (a `[]OperationDefinition`) as well as an `Options` property which is just the whole `Configuration` object.

This allows us to use Configuration values inside the template to conditionally render the template in different ways.

In this case, all I've done is gated the new mechanism for Chi middleware chaining behind the new Compatibility configuration variable `Options.Compatibility.ApplyChiMiddlewareFirstToLast`.

```go
{{if $.Options.Compatibility.ApplyChiMiddlewareFirstToLast}}
for i := len(siw.HandlerMiddlewares) -1; i >= 0; i-- {
  handler = siw.HandlerMiddlewares[i](handler)
}
{{else}}
for _, middleware := range siw.HandlerMiddlewares {
  handler = middleware(handler)
}
{{end}}
```

To start, we can have this be an opt-in compatibility option but using this new method of template rendering, it should be trivial to make the first-to-last chaining order an opt-out when we decide enough time has passed to establish it as the default.

This will also open up the ability to have template-specific feature flags in configuration that don't require maintaining lots of additional templates but just feature Option gating logic inside the templates instead.

2022-10-20 18:07 UTC, deepmap-marcinr commented
That's a lot of work you did, but options are globally stored on `globalstate.options`, precisely because it's a pain to pass them around everywhere, so your change can be done without all the changes to all the templates. All you really need to change is that one chi template and pass it an additional flag in its context, rather than changing all of them.

2022-10-20 23:59 UTC, ericvolp12 commented
> That's a lot of work you did, but options are globally stored on `globalstate.options`, precisely because it's a pain to pass them around everywhere, so your change can be done without all the changes to all the templates. All you really need to change is that one chi template and pass it an additional flag in its context, rather than changing all of them.

Okay, I didn't see that getting injected as a Template Func, thanks for the pointer!

In other news, I learned what Go Template Funcs are today!

Hopefully this change is a lot simpler and makes more sense, the activation functionality is the same but we're eschewing all my previous changes that were injecting options a second time.

2022-10-21 00:01 UTC, ericvolp12 commented
I saw this line while Go Generating locally:
```
go generate ./...
go: downloading github.com/matryer/moq v0.2.7
```

Looks like something got updated that the CI is unhappy with there?

2022-10-22 15:38 UTC, deepmap-marcinr commented
> 

It looks like a dependency got updated, it's no big deal, you just haven't fetched it before.

2022-10-22 17:06 UTC, ericvolp12 commented
> It looks like a dependency got updated, it's no big deal, you just haven't fetched it before.

Does this look okay to merge now or is there anything else you'd like me to change?

2022-10-22 18:22 UTC, deepmap-marcinr commented on pkg/codegen/templates/chi/chi-middleware.tmpl
> +  {{if opts.Compatibility.ApplyChiMiddlewareFirstToLast}}
I must be missing something - how does `opts` get passed in here? When we call GenerateChiServer, we pass in an array of OperationDefinition, which doesn't have opts.

2022-10-22 18:24 UTC, deepmap-marcinr commented on pkg/codegen/templates/chi/chi-middleware.tmpl
> +  {{if opts.Compatibility.ApplyChiMiddlewareFirstToLast}}
Oh, nevermind, I see it. This code has changed so much since I wrote it, I get lost sometimes.

2022-10-22 18:24 UTC, merged

2022-10-22 18:25 UTC, deepmap-marcinr commented
Yep, I merged it, thank you.

I'm looking to do a new release soon, just waiting on some PR wrapup.

________________________________________
From: Eric Volpert ***@***.***>
Sent: Saturday, October 22, 2022 10:06 AM
To: deepmap/oapi-codegen
Cc: Marcin Romaszewicz; Comment
Subject: Re: [deepmap/oapi-codegen] Chain Chi middlewares in reverse order so they execute first-to-last (PR #787)

It looks like a dependency got updated, it's no big deal, you just haven't fetched it before.

Does this look okay to merge now or is there anything else you'd like me to change?

—
Reply to this email directly, view it on GitHub<https://github.com/deepmap/oapi-codegen/pull/787#issuecomment-1287856958>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALKC5DGJ5OBZVPF4H777WWTWEQNINANCNFSM6AAAAAARE46H4A>.
You are receiving this because you commented.Message ID: ***@***.***>